#pragma once

#define IR_REMOTE_PIN 14
#define RANGEFINDER_ECHO_PIN 17
#define RANGEFINDER_TRIG_PIN 12
#define GRIPPER_POT_PIN 18

#define DRIVE_KP 50
// TODO: Tune liftKP
#define LIFT_KP 1
#define MAX_POWER 400
#define BASE_MAX_DRIVE_POWER 120
#define BASE_MAX_LIFT_POWER 400
#define DRIVE_TOLERANCE 1
// TODO: CALCULATE LIFT TOLERANCE
#define LIFT_TOLERANCE 2
#define DRIVE_DEADBAND 50 
#define LIFT_DEADBAND 350
#define TICKS_PER_LIFT_OUTPUT_DEGREE 96

#define CROSS_PASSING_DIST 7
#define TURN_OFF_LINE_ANGLE 60

#define LEFT_LINE_PIN 20
#define RIGHT_LINE_PIN 22
#define BLACK_THRESH 400
#define LINE_FOLLOW_SPEED 80
#define LINE_FOLLOW_KP 0.05

#define IR_BUTTON_START 0x04 // setup
#define IR_BUTTON_PAUSE 0x01 // play/pause
#define IR_BUTTON_RESUME 0x05 // prev/up
#define IR_BUTTON_STOP 0x06 // stop/mode
#define IR_BUTTON_RESET 0x0E // back

#define TRANSFER_BLOCK_ANGLE 0
#define ROOF_25_ANGLE 135
#define ROOF_25_LIFTED_ANGLE 95
#define ROOF_25_FINAL_ANGLE 122
#define ROOF_45_ANGLE 87

#define GRIPPER_TIMEOUT 2000
#define GRIPPER_OPEN_MS 2800
#define GRIPPER_OPEN_POT 440
#define GRIPPER_CLOSED_MS 550
#define GRIPPER_CLOSED_POT 250

#define RANGE_EARLY_APPROACH_TOWER 24
#define RANGE_LATE_APPROACH_TOWER 21

#define FINAL_APPROACH_WAIT_TIME 3000
#define WAIT_FOR_GRIPPER_LIFT_TIME 3000
#define FOLLOW_LINE_TILL_POINTED_AT_BOX_TIME 2000
#define BACK_UP_AFTER_PICKUP -4

#define TRANSFER_DROPOFF_OFFSET 10.795
#define TRANSFER_DROPOFF_LIFT_ANGLE -4
#define TRANSFER_BACKOFF -6
#define LIFT_ANGLE_AT_PICKUP 2

enum OperatingState
{
  Operating_Idle,
  Operating_Running,
  Operating_Paused,
  Operating_Done
} operatingState;
